### ISSUE TITLE
只支持IE浏览器吗？

### ISSUE THREAD

**Issue by caopengfei** [hemiaoio/Hamazon.Swagger.Ui#2]
使用360极速浏览器时，样式打乱，只支持IE浏览器吗？
Swashbuckle.AspNetCore.Swagger的版本是1.2

**Comment by hemiaoio** [comment]
没试过360浏览器，我使用的是chrome，样式 与 Swashbuckle.AspNetCore.Swagger 版本无关。
理论上IE 9以上，Chrome，Firefox, Opera 以及 Safari 都是兼容的。
